Repository noahcoomer/BlockchainPKI, pull requests merged in 2019-03, with the labels that each got.

#13 Updating validator class to support peer-to-peer receive/send
  .gitignore
  requirements.txt
  src/data/__init__.py
  src/network/__init__.py
  src/network/client.py
  src/network/validator.py
  src/test/__init__.py
Labels: enhancement, good first issue

#21 Adding functionality for unbound validators
  src/network/validator.py
Labels: enhancement

#24 Refactoring networking implementation to separate class
  requirements.txt
  src/network/client.py
  src/network/net.py
  src/network/validator.py
Labels: enhancement

#31 Docs, constructor changes, and test fixes
  docs/blockchain-diagram-top-down.png
  src/data_structs/block.py
  src/data_structs/blockchain.py
  src/data_structs/transaction.py
  src/network/client.py
  src/network/validator.py
  src/test/test_data_structs.py
  src/test/test_main.py
  src/test/test_pki.py
Labels: enhancement

#32 pycryptodome should be the only requirement
  requirements.txt
Labels: invalid

#33 Add Methods to Calculate Merkel Root from Transactions
  src/data_structs/block.py
  src/data_structs/blockchain.py
  src/test/__init__.py
  src/test/test_transaction.py
Labels: enhancement

#46 Fixed SSL functionality and deserializing data sent through the network
  src/validator.py
Labels: enhancement
